### numpy Numerical Python의 약자
### 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
### 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
### 정교한 브로드캐스팅 기능
### 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리(C언어 기반 라이브러리)
### 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
### 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [2]:
import numpy as np
np.__version__

'1.23.2'

In [8]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[4 5 6 4 5]


In [13]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0],a2[1,1],a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [20]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


## 배열 생성 및 초기화

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.ones(10)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.full((3,3),1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [29]:
# 단위행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# 삼각행렬
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* #### empty() : 초기화되지 않은 배열 생성  
>초기화가 없어서 배열 생성비용 저렴하고 빠름  
>초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [32]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* <h4>_like() : 지정된 배열과 shape가 같은 행렬 생성</h4>   
> np.zeros_like(), np.ones_like(), np.full_like()

In [33]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [34]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [35]:
print(a3)
np.full_like(a3,10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

* #### 생성한 값으로 배열 생성
> arange() : 정수 범위로 배열 생성  
> linspace() : 범위 내에서 균등 간격의 배열 생성  
> logspace() : 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [37]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [38]:
np.linspace(0, 1, 5) # 0 ~ 1 을 5등분 해라

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [40]:
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

* ### 랜덤값으로 배열 생성

In [42]:
# 랜덤한 수의 배열 생성
np.random.random((3,3))

array([[0.8107653 , 0.75828363, 0.58910934],
       [0.66031709, 0.08143957, 0.07913617],
       [0.01405114, 0.61246924, 0.87030425]])

In [43]:
# 일정 구간의 랜덤 정수의 배열 생성
np.random.randint(0, 10, (3, 3))

array([[0, 2, 3],
       [2, 7, 3],
       [5, 5, 0]])

* random.normal() : 정규분포를 고려한 랜덤한 수의 배열 생성  
* 평균 = 0, 표준편차 = 1 , 3 x 3 배열

In [44]:
np.random.normal(0,1,size=(3,3))

array([[-0.65173134,  0.52543989,  0.10360086],
       [-0.73624762,  1.571639  ,  0.79189425],
       [ 1.69907171,  0.49118593,  0.58772459]])

* random.rand() : 균등분포를 고려한 랜덤한 수의 배열 생성

In [45]:
np.random.rand(3,3)

array([[0.38835756, 0.50257275, 0.75338047],
       [0.91645067, 0.19609359, 0.54002834],
       [0.6731894 , 0.73930271, 0.26007151]])

* random.randn() : 표준정규분포를 고려한 랜덤한 수의 배열 생성

In [46]:
np.random.randn(3,3)

array([[-1.77858281,  0.83827954, -0.97091732],
       [-2.10376806, -0.8120491 , -1.44337895],
       [ 1.3742728 ,  1.02730825, -0.28153232]])

## 표준 데이터 타입

In [47]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [50]:
np.full((3,3),1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 날짜 시간 정보 배열

In [51]:
date = np.array('2020-01-01',dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [52]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [54]:
datetime = np.datetime64('2022-09-19 12:00')
datetime

numpy.datetime64('2022-09-19T12:00')

In [56]:
datetime2 = np.datetime64('2022-09-19 16:21:14.56','ns') #나노초
datetime2

numpy.datetime64('2022-09-19T16:21:14.560000000')